[workspace]
resolver = "2"
members = [
    "s3",
    "aws-region",
    "aws-creds"
]

[workspace.package]
license = "MIT"

[workspace.dependencies]
thiserror = "1"
env_logger = "0.11"

[profile.release]
lto = "fat"
