[graph]
all-features = true

[advisories]
version = 2
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # "RUSTSEC-0000-0000"
]

[licenses]
version = 2
allow = [
    "MIT",
    "ISC",
    "OpenSSL",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016", # used by unicode-ident
    "CC0-1.0",
    "MPL-2.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
skip = [
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]
allow-git = []
